# generated by cabal-rpm-2.2.2
# https://docs.fedoraproject.org/en-US/packaging-guidelines/Haskell/

# workaround "Empty %files file BUILD/MicroHs-0.8.4.0/debugsourcefiles.list"
%define debug_package %{nil}

# fails on i686

# currently not fully wired up
%bcond_with ghc
%bcond_without compiler_bootstrap

Name:           MicroHs
Version:        0.11.4.0
Release:        1%{?dist}
Summary:        A small compiler for Haskell

License:        Apache-2.0
Url:            https://hackage.haskell.org/package/MicroHs
# Begin cabal-rpm sources:
Source0:        https://hackage.haskell.org/package/%{name}-%{version}/%{name}-%{version}.tar.gz
# End cabal-rpm sources
Source1:        mhs.in

# Begin cabal-rpm deps:
%if %{with ghc}
BuildRequires:  ghc-Cabal-devel
BuildRequires:  ghc-rpm-macros
BuildRequires:  ghc-base-devel
BuildRequires:  ghc-deepseq-devel
BuildRequires:  ghc-directory-devel
BuildRequires:  ghc-filepath-devel
BuildRequires:  ghc-haskeline-devel
BuildRequires:  ghc-process-devel
BuildRequires:  ghc-text-devel
BuildRequires:  ghc-time-devel
%else
BuildRequires:  gcc
BuildRequires:  gmp-devel
BuildRequires:  make
%endif
# End cabal-rpm deps
ExcludeArch:    %{ix86}

%description
A compiler for an extended subset of Haskell-2010. The compiler translates to
combinators and can compile itself.


%prep
# Begin cabal-rpm setup:
%setup -q
# End cabal-rpm setup


%build
%if %{with ghc}
# Begin cabal-rpm build:
%ghc_bin_build
# End cabal-rpm build
%else
make %{?with_compiler_bootstrap:bootstrap} bin/cpphs
%endif

%install
%if %{with ghc}
# Begin cabal-rpm install
%ghc_bin_install
# End cabal-rpm install
%else
%define mhsdir %{_libdir}/mhs-%{version}
make oldinstall PREFIX=%{buildroot}%{mhsdir}

mkdir %{buildroot}%{_bindir}
install %{SOURCE1} %{buildroot}%{_bindir}/mhs
sed -i -e 's!@PREFIX@!%{mhsdir}!' %{buildroot}%{_bindir}/mhs
%endif


%check
MHS_PREFIX=%{buildroot}%{mhsdir} %{buildroot}%{_bindir}/mhs Example -oEx
./Ex
MHS_PREFIX=%{buildroot}%{mhsdir} %{buildroot}%{_bindir}/mhs Example -r
#missing /bin/sh: line 1: errmsg.test: No such file or directory
# make runtest


%files
# Begin cabal-rpm files:
%license LICENSE
%doc README.md
%{_bindir}/mhs
%{mhsdir}
# End cabal-rpm files


%changelog
* Fri Feb 21 2025 Jens Petersen  <petersen@redhat.com> - 0.11.4.0-1
- update to 0.11.4

* Fri Jan 10 2025 Jens Petersen <petersen@redhat.com> - 0.10.7.0-1
- update to 0.10.7

* Sat Sep  7 2024 Jens Petersen <petersen@redhat.com> - 0.9.17.0-1
- update to 0.9.17

* Fri Jul 19 2024 Jens Petersen <petersen@redhat.com> - 0.9.13.0-1
- update to 0.9.13

* Tue Apr 16 2024 Jens Petersen <petersen@redhat.com> - 0.9.8.0-1
- update to 0.9.8

* Sat Jan 27 2024 Jens Petersen <petersen@redhat.com> - 0.9.3.0-1
- update to 0.9.3

* Sun Nov 26 2023 Jens Petersen <petersen@redhat.com> - 0.8.4.0-1
- spec file generated by cabal-rpm-2.1.5
